/* eslint-disable react-hooks/set-state-in-effect */
"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import NovaTopBar from "../../../components/NovaTopBar";
import { deleteCurrentUser, getCurrentUser, signOutUser } from "../../../lib/nova-auth";
import { useNovaSettings } from "../../settings-context";
import "../mobile.css";
export default function MobileSettingsPage(){const router=useRouter();const {theme,setTheme,language,setLanguage}=useNovaSettings();const [user,setUser]=useState<ReturnType<typeof getCurrentUser>>(null);const [confirm,setConfirm]=useState(false);useEffect(()=>{const u=getCurrentUser();if(!u){router.replace("/mobile/login");return;}setUser(u)},[router]);if(!user)return null;const logout=()=>{signOutUser();router.replace("/mobile/login")};const remove=()=>{if(!confirm){setConfirm(true);return;}deleteCurrentUser();router.replace("/mobile/login")};return <main className={`mobile-page theme-${theme}`}><NovaTopBar statusText="AI 시스템 준비" /><div className="mobile-page-title"><h1>설정</h1><p>언어·테마·계정 설정</p></div><section className="mobile-content-card mobile-settings-card"><div className="mobile-setting-row"><span>언어</span><div><button className={language==="ko"?"selected":""} onClick={()=>setLanguage("ko")}>한국어</button><button className={language==="en"?"selected":""} onClick={()=>setLanguage("en")}>English</button></div></div><div className="mobile-setting-row"><span>테마</span><div>{(["dark","white","ivory"] as const).map(t=><button key={t} className={theme===t?"selected":""} onClick={()=>setTheme(t)}>{t==="dark"?"다크":t==="white"?"화이트":"아이보리"}</button>)}</div></div><div className="mobile-setting-row"><span>계정</span><strong>{user.email}</strong></div><button className="mobile-secondary-button mobile-full-button" onClick={()=>router.push("/mobile/profile")}>프로필 수정</button><button className="mobile-secondary-button mobile-full-button" onClick={()=>router.push("/mobile/billing")}>결제 관리</button><button className="mobile-secondary-button mobile-full-button" onClick={()=>router.push("/mobile/inquiry")}>1:1 문의</button><button className="mobile-secondary-button mobile-full-button" onClick={logout}>로그아웃</button><button className="mobile-danger-button" onClick={remove}>{confirm?"정말 탈퇴하기":"회원 탈퇴"}</button>{confirm&&<p className="mobile-note">탈퇴를 진행하면 현재 계정과 연결된 로컬 데이터가 삭제됩니다.</p>}</section></main>}
