"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { getAthleteProfile, getCurrentUser, saveAthleteProfile, updateCurrentUserProfile, type NovaUser } from "../../../lib/nova-auth";
import "../mobile.css";

export default function MobileProfilePage() {
  const router=useRouter(); const [user,setUser]=useState<NovaUser|null>(null); const [name,setName]=useState(""); const [email,setEmail]=useState("");
  const [athlete,setAthlete]=useState({height:"",weight:"",bodyFat:"",position:"",injuryHistory:""}); const [message,setMessage]=useState("");
  useEffect(()=>{const u=getCurrentUser(); if(!u){router.replace("/mobile/login");return;} setUser(u);setName(u.name);setEmail(u.email);const p=getAthleteProfile(u.id);if(p)setAthlete({height:p.height==null?"":String(p.height),weight:p.weight==null?"":String(p.weight),bodyFat:p.bodyFat==null?"":String(p.bodyFat),position:p.position??"",injuryHistory:p.injuryHistory??""});},[router]);
  const submit=(e:FormEvent)=>{e.preventDefault();if(!user)return;const u=updateCurrentUserProfile({name,email});if(!u){setMessage("이름과 이메일을 확인하세요. 이미 사용 중인 이메일일 수 있습니다.");return;}if(user.role==="athlete")saveAthleteProfile({userId:user.id,height:athlete.height?Number(athlete.height):undefined,weight:athlete.weight?Number(athlete.weight):undefined,bodyFat:athlete.bodyFat?Number(athlete.bodyFat):undefined,position:athlete.position.trim()||undefined,injuryHistory:athlete.injuryHistory.trim()||undefined});setUser(u);setMessage("프로필이 저장되었습니다.");};
  if(!user)return null;
  return <main className={`mobile-page theme-ivory`}><header className="mobile-subheader"><div className="mobile-desktop-header"><div className="mobile-desktop-header-left"><button onClick={()=>router.push("/mobile")} aria-label="뒤로">←</button><div className="mobile-desktop-brand"><strong>N O V A</strong><span>AI SPORTS PERFORMANCE PLATFORM</span></div></div><div className="mobile-ai-status"><i></i> AI 시스템 준비</div></div><div className="mobile-page-title"><span className="mobile-eyebrow">NOVA SPORTS AI · MOBILE</span><h1>프로필</h1><p>계정과 선수 정보를 수정합니다.</p></div></header><section className="mobile-content-card mobile-account-card"><form onSubmit={submit} className="mobile-account-form"><label>이름<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>이메일<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><div className="mobile-role-summary"><strong>역할</strong><span>{user.role==="director"?"감독":user.role==="coach"?"코치":user.role==="athlete"?"선수":user.role==="parent"?"학부모":"관리자"}</span></div>{user.role==="athlete"&&<div className="mobile-profile-edit-grid"><label>키 (cm)<input value={athlete.height} onChange={e=>setAthlete(v=>({...v,height:e.target.value}))}/></label><label>체중 (kg)<input value={athlete.weight} onChange={e=>setAthlete(v=>({...v,weight:e.target.value}))}/></label><label>체지방률<input value={athlete.bodyFat} onChange={e=>setAthlete(v=>({...v,bodyFat:e.target.value}))}/></label><label>포지션<input value={athlete.position} onChange={e=>setAthlete(v=>({...v,position:e.target.value}))}/></label><label>부상 이력<input value={athlete.injuryHistory} onChange={e=>setAthlete(v=>({...v,injuryHistory:e.target.value}))}/></label></div>}<button className="mobile-action-button" type="submit">프로필 저장</button>{message&&<p className="mobile-note">{message}</p>}</form></section></main>;
}
